name: crimea-rag

services:
  crimea-rag:
    build:
      context: .
      dockerfile: Dockerfile
    image: chainlit_crimea-rag:${DOCKER__APP_VERSION}
    pull_policy: missing
    container_name: chainlit_crimea-rag_app
    restart: always
    env_file:
      - .env
    volumes:
      - ./database:/app/database
      - ./public:/app/public
    ports:
      - "8001:8000"
